spring:
  datasource:
    url: jdbc:mysql://localhost-3307/databaseHere?createDatabaseIfNotExist = true
    username: add your username
    password: add your password here

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true